CIDADES = [
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Salvador",
    "Fortaleza",
    "Brasília",
    "Curitiba",
    "Manaus",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Goiânia",
    "João Pessoa",
    "Natal",
    "Maceió",
    "Teresina",
    "Campo Grande",
    "Cuiabá",
    "Aracaju",
    "São Luís",
    "Florianópolis",
    "Vitória",
    "Macapá",
    "Palmas",
    "Boa Vista",
    "Porto Velho",
    "Rio Branco",
    "Santos",
    "Campinas",
    "Sorocaba",
    "Niterói",
    "Caxias do Sul",
    "Londrina",
    "Maringá",
    "Joinville",
    "Blumenau",
    "Uberlândia",
    "Ribeirão Preto",
    "São José dos Campos",
    "Santo André",
    "Osasco",
    "Jundiaí",
    "Piracicaba",
    "Bauru",
    "São José do Rio Preto",
    "Mogi das Cruzes",
    "Volta Redonda",
    "Petrópolis",
    "Campos dos Goytacazes",
]

PROFISSOES = [
    "Autônomo",
    "Estagiário",
    "Jovem Aprendiz",
    "Freelancer",
    "Empreendedor",
    "Voluntário",
    "Pensionista",
    "Freelancer Júnior",
    "Profissional Liberal",
    "Trabalhador Informal",
    "Freelancer Pleno",
    "Freelance Part-Time",
    "Professor",
    "Engenheiro Civil",
    "Enfermeiro",
    "Advogado",
    "Agricultor",
    "Médico",
    "Enfermeiro",
    "Fisioterapeuta",
    "Dentista",
    "Psicólogo",
    "Nutricionista",
    "Farmacêutico",
    "Biomédico",
    "Fonoaudiólogo",
    "Veterinário",
]

PROFISSOES_PROGRAMACAO = [
    "Programador",
    "Desenvolvedor Front-End",
    "Desenvolvedor Back-End",
    "Desenvolvedor Full-Stack",
    "Engenheiro de Software",
    "Analista de Sistemas",
    "Desenvolvedor de Aplicativos",
    "Cientista de Dados",
    "Engenheiro de Dados",
    "Desenvolvedor de Jogos",
    "Arquiteto de Software",
    "Desenvolvedor Mobile",
    "Desenvolvedor Web",
    "Engenheiro de Machine Learning",
    "Engenheiro de Inteligência Artificial",
    "DevOps",
    "Desenvolvedor de Firmware",
    "Desenvolvedor de Banco de Dados",
    "Engenheiro de Automação",
    "Analista de Segurança da Informação",
    "Desenvolvedor de Sistemas Embarcados",
    "Engenheiro de Cloud",
    "Engenheiro de Rede",
]

LINGUAGENS_PROGRAMACAO = [
    "Python",
    "Java",
    "C++",
    "PHP",
    "C",
    "C#",
    "JavaScript",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "TypeScript",
    "R",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "Lua",
    "Objective-C",
    "MATLAB",
    "Visual Basic",
    "Julia",
    "Elixir",
    "Erlang",
    "F#",
    "Scheme",
    "Prolog",
    "Assembly",
    "SQL",
    "Shell",
    "Groovy",
    "COBOL",
    "Fortran",
    "Ada",
    "Pascal",
    "VHDL",
    "Verilog",
    "SAS",
    "LabVIEW",
    "Lisp",
    "OCaml",
    "Scratch",
    "Smalltalk",
    "Tcl",
    "ABAP",
    "Delphi/Object Pascal",
    "Crystal",
    "Nim",
    "Solidity",
    "Zig",
    "Powershell",
]
