USUARIOS = []

PROFISSOES = [
    "Autônomo",
    "Estagiário",
    "Jovem Aprendiz",
    "Freelancer",
    "Empreendedor",
    "Voluntário",
    "Pensionista",
    "Freelancer Júnior",
    "Profissional Liberal",
    "Trabalhador Informal",
    "Freelancer Pleno",
    "Freelance Part-Time",
    "Professor",
    "Engenheiro Civil",
    "Enfermeiro",
    "Advogado",
    "Agricultor",
    "Médico",
    "Enfermeiro",
    "Fisioterapeuta",
    "Dentista",
    "Psicólogo",
    "Nutricionista",
    "Farmacêutico",
    "Biomédico",
    "Fonoaudiólogo",
    "Veterinário",
]

PROFISSOES_PROGRAMACAO = [
    "Programador",
    "Desenvolvedor Front-End",
    "Desenvolvedor Back-End",
    "Desenvolvedor Full-Stack",
    "Engenheiro de Software",
    "Analista de Sistemas",
    "Desenvolvedor de Aplicativos",
    "Cientista de Dados",
    "Engenheiro de Dados",
    "Desenvolvedor de Jogos",
    "Arquiteto de Software",
    "Desenvolvedor Mobile",
    "Desenvolvedor Web",
    "Engenheiro de Machine Learning",
    "Engenheiro de Inteligência Artificial",
    "DevOps",
    "Desenvolvedor de Firmware",
    "Desenvolvedor de Banco de Dados",
    "Engenheiro de Automação",
    "Analista de Segurança da Informação",
    "Desenvolvedor de Sistemas Embarcados",
    "Engenheiro de Cloud",
    "Engenheiro de Rede",
]

LINGUAGENS_PROGRAMACAO = [
    "Python",
    "Java",
    "C++",
    "PHP",
    "C",
    "C#",
    "JavaScript",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "TypeScript",
    "R",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "Lua",
    "Objective-C",
    "MATLAB",
    "Visual Basic",
    "Julia",
    "Elixir",
    "Erlang",
    "F#",
    "Scheme",
    "Prolog",
    "Assembly",
    "SQL",
    "Shell",
    "Groovy",
    "COBOL",
    "Fortran",
    "Ada",
    "Pascal",
    "VHDL",
    "Verilog",
    "SAS",
    "LabVIEW",
    "Lisp",
    "OCaml",
    "Scratch",
    "Smalltalk",
    "Tcl",
    "ABAP",
    "Delphi/Object Pascal",
    "Crystal",
    "Nim",
    "Solidity",
    "Zig",
    "Powershell",
]


DIAS_SEMANA = {
    0: 'Segunda-feira',
    1: 'Terça-feira',
    2: 'Quarta-feira',
    3: 'Quinta-feira',
    4: 'Sexta-feira',
    5: 'Sábado',
    6: 'Domingo'
}

MESES = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}


